<a href="https://colab.research.google.com/github/CoderVudu/06_Python_Numpy_Assignment_Sharmistha_Dey./blob/main/06_Python_Numpy_Assignment_Sharmistha_Dey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Theoretical Questions:


##Q 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy is a foundational library in Python for scientific computing and data analysis, offering a powerful array object that enhances Python’s capabilities for handling numerical data. Its core purpose is to provide efficient and flexible tools for performing mathematical and logical operations on large datasets. NumPy arrays enable faster computations than standard Python lists by storing elements in contiguous memory locations, which minimizes overhead and supports vectorized operations, where entire arrays are processed simultaneously rather than element by element.

Advantages of NumPy include built-in functions for array manipulation, linear algebra, and random number generation, making it suitable for handling multidimensional data, performing complex calculations, and creating custom algorithms. Additionally, NumPy seamlessly integrates with other scientific libraries like SciPy and Pandas, further extending its utility in machine learning, statistics, and data science. By optimizing speed and memory use, NumPy is crucial for large-scale data processing and advanced numerical analysis in Python.

##Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In NumPy, `np.mean()` calculates the arithmetic mean of an array’s elements, treating all elements equally by default. It’s straightforward and ideal when a simple average is required. Conversely, `np.average()` can compute a weighted average if weights are provided, allowing for specific elements to contribute more significantly to the result. Without weights, `np.average()` behaves like `np.mean()`.

Use `np.mean()` for unweighted data or when weights aren’t relevant, as it's simpler and faster. Choose `np.average()` when different elements should have varying levels of influence, such as in financial or statistical calculations involving weighted values.

##Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In NumPy, arrays can be reversed along different axes using slicing or specific functions like `np.flip`.

For a **1D array**, reversing is straightforward using slicing `[::-1]`. For example:
```python
import numpy as np
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]  # Output: [4, 3, 2, 1]
```

For a **2D array**, reversing along the rows or columns can be done with slicing or `np.flip`:
1. **Reversing rows** (axis 0):
   ```python
   arr2D = np.array([[1, 2], [3, 4]])
   reversed_rows = arr2D[::-1, :]  # Output: [[3, 4], [1, 2]]
   ```

2. **Reversing columns** (axis 1):
   ```python
   reversed_cols = arr2D[:, ::-1]  # Output: [[2, 1], [4, 3]]
   ```

Alternatively, `np.flip(arr2D, axis=0)` flips along rows, and `np.flip(arr2D, axis=1)` along columns, providing a flexible approach for multi-dimensional arrays.

##Q 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

To determine the data type of elements in a NumPy array, use the `.dtype` attribute, which reveals the array's data type. Data types are critical in memory management and performance because they define how much memory each element occupies. For instance, `int32` uses 4 bytes, while `int64` uses 8 bytes. Choosing the smallest suitable data type minimizes memory usage, allowing larger arrays to fit into memory and improving computation speed. Additionally, matching data types with operations enhances efficiency, as NumPy’s vectorized operations are optimized for specific data types, resulting in faster execution.

##Q 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (n-dimensional array) is a powerful, multidimensional container for homogeneous data, meaning all elements must be of the same data type. Ndarrays support complex mathematical operations and broadcasting, allowing efficient element-wise operations without explicit loops. Key features include high performance due to contiguous memory allocation, vectorized operations, and extensive functionality for data manipulation, reshaping, and slicing. Unlike Python lists, ndarrays consume less memory, enable faster computations, and are designed for numerical tasks. Lists, while flexible in types, lack such optimized operations, making them less suitable for large-scale numeric processing and scientific computing.

##Q 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance advantages over Python lists for large-scale numerical operations due to their efficient memory management and optimized, compiled C code. Unlike lists, NumPy arrays store elements of the same data type in contiguous memory, enabling rapid data access and manipulation. This homogeneity allows for vectorized operations, where element-wise calculations are executed without Python loops, reducing overhead and boosting speed. NumPy also leverages low-level optimizations, such as SIMD (Single Instruction, Multiple Data) and parallel processing. These features result in substantial performance improvements, especially for high-dimensional data and large-scale computations common in scientific and numerical applications.

##Q 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, `vstack()` and `hstack()` are used to stack arrays vertically and horizontally, respectively. `vstack()` combines arrays row-wise, increasing the number of rows, while `hstack()` stacks them column-wise, increasing the number of columns.

For example:

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack
v = np.vstack((a, b))  # Output: [[1, 2, 3], [4, 5, 6]]

# Horizontal stack
h = np.hstack((a, b))  # Output: [1, 2, 3, 4, 5, 6]
```

`vstack()` is useful for creating multi-row matrices, while `hstack()` is helpful for concatenating arrays side-by-side.

##Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy, `fliplr()` and `flipud()` are array flipping methods with distinct behaviors. `fliplr()` flips a 2D array horizontally, reversing the order of elements along the last axis (columns). For example, an array's first column becomes its last. This function requires an array with at least two dimensions.

On the other hand, `flipud()` flips an array vertically by reversing elements along the first axis (rows), making the top row the bottom. Unlike `fliplr()`, `flipud()` works on any array with one or more dimensions. Both methods maintain array shape while reordering elements.

##Q 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The `array_split()` method in NumPy divides an array into specified subarrays. Unlike `split()`, which requires equal-sized splits, `array_split()` handles cases where the array cannot be evenly divided. It creates subarrays of approximately equal size, distributing any remaining elements across the initial subarrays. For example, if an array of length 10 is split into 3 parts, `array_split()` will return subarrays of lengths 4, 3, and 3, respectively, rather than failing. This makes it particularly useful when handling data that may not divide evenly, enabling flexible partitioning without error.

##Q 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In NumPy, **vectorization** allows operations to be applied to entire arrays without explicit loops, harnessing optimized C code for faster execution. This avoids Python’s loop overhead and results in concise, efficient code. **Broadcasting** enables arithmetic operations on arrays of different shapes by “stretching” smaller arrays to match larger ones, without creating redundant copies. Together, vectorization and broadcasting improve computational efficiency by leveraging underlying optimizations and memory management, which is essential for large-scale data processing and scientific computing. These techniques allow NumPy to perform complex array operations quickly and with minimal code.

#Practical Questions:

##Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("Transposed Array:\n", transposed_array)


Original Array:
 [[86 88 66]
 [24 32 98]
 [42 33 33]]
Transposed Array:
 [[86 24 42]
 [88 32 33]
 [66 98 33]]


##Q 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the 1D array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)


1D Array: [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##Q 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np

# Create a 4x4 array with random floats
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print(array_6x6)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.953102   0.17775874 0.13818275 0.92959594 0.        ]
 [0.         0.82630584 0.45998036 0.3545826  0.65249082 0.        ]
 [0.         0.40364726 0.29760576 0.13270522 0.87932341 0.        ]
 [0.         0.99410717 0.60430854 0.39528338 0.82366539 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Display the array
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


##Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
# Use np.char.upper() to apply the upper() method to each element of the array
uppercase = np.char.upper(arr)     # Uppercase
lowercase = np.char.lower(arr)     # Lowercase
titlecase = np.char.title(arr)     # Title case
capitalize = np.char.capitalize(arr)  # Capitalize

# Display the results
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)
print("Capitalize:", capitalize)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


##Q 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.




In [7]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


##Q 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.




In [8]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise operations
addition = array1 + array2           # Addition
subtraction = array1 - array2        # Subtraction
multiplication = array1 * array2     # Multiplication
division = array1 / array2           # Division

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


##Q 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


##Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [10]:
import numpy as np

# Generate an array of 100 random integers
random_integers = np.random.randint(0, 1001, 100)

# Function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Filter and display prime numbers
prime_numbers = [num for num in random_integers if is_prime(num)]
print(prime_numbers)


[71, 59, 233, 937, 677, 607, 439, 71, 647, 461, 521, 587, 137, 433, 389, 421, 37, 487, 967]


##Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [12]:
import numpy as np

# Create an array of daily temperatures for 30 days
temperatures = np.random.randint(0, 35, size=30)

# Reshape the array into a shape compatible with the number of elements
# For example, reshape into 5 weeks of 6 days each (5 * 6 = 30)
weekly_temperatures = temperatures.reshape(5, 6)

# Calculate the average temperature for each week
weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures:", temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [34  6 20 31  5  2 14 17 15 18  1 12 19 16 19 29 18 21 13 13 30  7 25 26
 26  9  6 25 14  8]
Weekly Averages: [16.33333333 12.83333333 20.33333333 19.         14.66666667]
